# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eid', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('event_start_date', models.DateTimeField(validators=[events.models.validate_future_events])),
                ('event_end_date', models.DateTimeField(validators=[events.models.validate_future_events])),
                ('link', models.URLField()),
                ('description', models.TextField(max_length=1000)),
                ('venue', models.CharField(max_length=500)),
                ('registration_form_link', models.URLField()),
                ('event_image_link', models.URLField()),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
